name: CI

# Controls when the action will run.
on:
  schedule:
    - cron: "0 0 1 1 *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-readme:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # The environment variables the job relies on
    env:
      README_FILE: README.md

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Get the year
      - name: Store year information as environment variables
        run: |
          CURRENT_YEAR=$(date +'%Y')
          PREVIOUS_YEAR=$(($CURRENT_YEAR - 1))
          echo "CURRENT_YEAR=$CURRENT_YEAR" >> $GITHUB_ENV
          echo "PREVIOUS_YEAR=$PREVIOUS_YEAR" >> $GITHUB_ENV

      # Replace the year
      - name: Update the current year in code examples
        run: |
          cd $GITHUB_WORKSPACE
          sed -i "s/${{ env.PREVIOUS_YEAR }}/${{ env.CURRENT_YEAR }}/g" ${{ env.README_FILE }}

      # Add and commit changed README.md
      - uses: EndBug/add-and-commit@v7
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: ${{ env.README_FILE }}

          # The name of the user that will be displayed as the author of the commit
          # Default: author of the commit that triggered the run
          author_name: Lukas Besch

          # The email of the user that will be displayed as the author of the commit
          # Default: author of the commit that triggered the run
          author_email: connect@lukasbesch.com

          # Name of the branch to use, if different from the one that triggered the workflow
          # Default: the branch that triggered the run
          branch: master

          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: "📝 docs: Happy new year ${{ env.CURRENT_YEAR }}! 🎆"
